[package]
name = "openlock-totp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["thiserror/std"]

[dependencies]
hmac.workspace = true
sha2.workspace = true
subtle.workspace = true
zeroize.workspace = true
thiserror.workspace = true
