[package]
name = "openlock-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["openlock-types/std", "openlock-crypto/std", "thiserror/std"]

[dependencies]
openlock-types = { workspace = true, default-features = false }
openlock-crypto = { workspace = true, default-features = false }
ed25519-dalek.workspace = true
thiserror.workspace = true

[dev-dependencies]
rand_core.workspace = true
