[package]
name = "openlock-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["secure", "totp"]
secure = ["dep:openlock-core", "dep:openlock-protocol", "dep:openlock-types"]
totp = ["dep:openlock-totp"]

[dependencies]
openlock-core = { workspace = true, features = ["std"], optional = true }
openlock-protocol = { workspace = true, features = ["std"], optional = true }
openlock-types = { workspace = true, features = ["std"], optional = true }
openlock-totp = { workspace = true, features = ["std"], optional = true }
