[package]
name = "openlock-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
openlock-core = { path = "../openlock-core" }
openlock-protocol.workspace = true
openlock-types.workspace = true
