[package]
name = "openlock-issuer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
openlock-core = { path = "../openlock-core", features = ["std"] }
openlock-crypto = { workspace = true, features = ["std"] }
openlock-types = { workspace = true, features = ["std"] }
ed25519-dalek.workspace = true
